### ISSUE TITLE
Smartcontract Example

### ISSUE THREAD

**Issue by cscho** [LinkPoolio/iota-cl-ea#1]
Love what you've done here - it's a great example of how to start a LINK node with expressJS. 

I think it would be wonderful, for all potential users, if you included an example of how a solidity smartcontract can utilize this node. Demonstrate how do smartcontracts access these nodes.

**Comment by cscho** [comment]
After some investigation, it seems that the only way to create chainlink smartcontracts is create.smartcontract.com. If you can confirm this, you can close the issue as invalid.

**Comment by jleeh** [comment]
You currently can't use external adaptors on the create.smartcontract.com website. When the network is released, you'll be able to add this external adaptor to your node, but you run this adaptor as a separate service yourself.

I'll close this for now.
